# Generated by Django 4.2.3 on 2023-07-26 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221)),
            ],
        ),
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leetcode.category')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leetcode.difficulty')),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leetcode.descriptions')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leetcode.difficulty')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leetcode.problem')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='solutions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leetcode.solutions'),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leetcode.tag'),
        ),
        migrations.AddField(
            model_name='descriptions',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leetcode.problem'),
        ),
    ]
