# Generated by Django 4.2.3 on 2023-07-26 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='solutions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leetcode.solutions'),
        ),
    ]
